version: '3'

services:
  database:
    image: mysql:5.7.16
    container_name: database
    volumes:
      - ./var/lib/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
  
  app:
    build: .
    container_name: app
    ports:
      - 8080:80
      - 8443:443
